# Generated by Django 2.1.2 on 2022-02-11 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author_name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('publication', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('book_name',),
            },
        ),
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btype', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('btype',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.Booktype'),
        ),
    ]
